/**
 * Failure Mode Definitions for Eagle Size Simulator
 *
 * Failure modes are first-class entities representing discrete physiological
 * breakdown events that occur when scaling constraints exceed viable limits.
 */

import {
  WING_LOADING_THRESHOLD,
  BONE_THRESHOLD,
  POWER_THRESHOLD,
  THERMO_THRESHOLD,
} from './simDefaults';

// -- Types --------------------------------------------------------------------

export type FailureSeverity = 'hard' | 'catastrophic';
export type Subsystem = 'wingLoading' | 'bone' | 'power' | 'thermo';

export interface FailureModeDefinition {
  id: string;
  subsystem: Subsystem;
  severity: FailureSeverity;
  title: string;
  shortDescription: string;
  longDescription: string;
  recoveryHint: string | null;
  proxyThreshold: number;
}

export interface ScalingProxies {
  wingLoading: number;
  bone: number;
  power: number;
  thermo: number;
}

// -- Failure mode definitions -------------------------------------------------

export const FAILURE_MODES: Record<string, FailureModeDefinition> = {
  // =========================================================================
  // WING LOADING FAILURE
  // =========================================================================
  WING_LOADING_FAILURE: {
    id: 'WING_LOADING_FAILURE',
    subsystem: 'wingLoading',
    severity: 'catastrophic',
    title: 'Wing Loading Collapse',
    shortDescription: 'Cannot generate enough lift to sustain flight. The eagle is grounded.',
    longDescription: `
**The Physics of Failure**

Lift is generated by wings according to the equation:

**L = 0.5 * rho * v^2 * Cl * A**

where A is wing area, rho is air density, v is airspeed, and Cl is the lift coefficient. Wing area scales as L^2 (the square of body length), but body mass scales as L^3. This means wing loading -- the ratio of weight to wing area -- increases linearly with size.

**The Scaling Problem**

At baseline size, an eagle's wings generate plenty of lift at moderate airspeeds (30-40 m/s). But as the eagle grows:
- Mass increases as the **cube** of body length
- Wing area increases only as the **square**
- Required airspeed for level flight increases as the **square root** of wing loading

At some critical size, the minimum airspeed for level flight exceeds the structural limits of the wings and the metabolic capacity to sustain flapping.

**Why the Largest Flying Birds Are Near the Limit**

The Great Bustard (~18 kg) and Andean Condor (~15 kg) are among the heaviest flying birds alive today. They are right at the theoretical maximum -- bustards need long running takeoffs, and condors rely almost entirely on thermal soaring because powered flight is metabolically prohibitive. Argentavis magnificens (~72 kg, Miocene epoch) is near the absolute upper bound for a flying bird, and it was exclusively a soarer in a world with stronger thermals.

**The Result**

At this size, no amount of flapping can generate sufficient lift. The eagle's wings become decorative. It is permanently grounded.
    `.trim(),
    recoveryHint: 'Increase air density above 1.4 kg/m^3, or reduce gravity below 0.5g.',
    proxyThreshold: WING_LOADING_THRESHOLD,
  },

  // =========================================================================
  // BONE STRUCTURAL FAILURE
  // =========================================================================
  BONE_STRUCTURAL_FAILURE: {
    id: 'BONE_STRUCTURAL_FAILURE',
    subsystem: 'bone',
    severity: 'catastrophic',
    title: 'Pneumatized Bone Fracture',
    shortDescription: 'Hollow bones shatter under the weight. Structural collapse.',
    longDescription: `
**The Physics of Failure**

Bird bones are marvels of engineering: they are **pneumatized** -- hollow, filled with air sacs connected to the respiratory system. Internal struts (trabeculae) provide reinforcement, similar to the structure of aircraft wings. This saves enormous weight, which is critical for flight.

But this weight savings comes at a cost: reduced compressive and bending strength compared to solid mammalian bones.

**The Scaling Problem**

Bone cross-sectional area scales as L^2, but the forces on bones during landing, takeoff, and maneuvering scale as L^3 (proportional to mass). The stress on each bone increases linearly with size. For hollow bones, the failure point arrives sooner because less material is bearing the load.

The scaling exponent for bone failure is approximately s^1.5 because:
- Load scales as L^3
- Bone strength (cross-section * material strength) scales as L^2
- But pneumatization reduces effective material by ~L^0.5

**How Pterosaurs Got Around This**

Pterosaurs achieved wingspans of 10-12 meters (Quetzalcoatlus) through several adaptations:
- Extremely thin but geometrically optimized bone walls
- Fiber-reinforced bone microstructure different from birds
- Launch mechanism using quadrupedal vault (not bipedal takeoff)
- Many large pterosaurs had relatively small bodies with enormous wings

Even so, the largest pterosaurs were likely at the absolute structural limit.

**The Result**

At this size, the eagle's pneumatized skeleton cannot support its own weight. Landing from even a short glide would shatter leg bones. Wing spars would fracture during turbulence. The skeleton that once enabled flight now ensures destruction.
    `.trim(),
    recoveryHint: 'Reduce gravity below 0.3g to lower skeletal loading.',
    proxyThreshold: BONE_THRESHOLD,
  },

  // =========================================================================
  // METABOLIC POWER DEFICIT
  // =========================================================================
  METABOLIC_POWER_DEFICIT: {
    id: 'METABOLIC_POWER_DEFICIT',
    subsystem: 'power',
    severity: 'hard',
    title: 'Metabolic Power Deficit',
    shortDescription: 'Cannot generate enough power for sustained flight.',
    longDescription: `
**The Physics of Failure**

The power required for flapping flight scales approximately as M^(7/6) -- slightly faster than linearly with mass. But the maximum sustained metabolic power output of an animal scales as M^0.75 (Kleiber's Law). The gap between power required and power available widens relentlessly with size.

**The Energy Budget**

For a 4.5 kg bald eagle:
- Basal metabolic rate: ~15 W
- Maximum sustained flight power: ~60-80 W
- Power margin for maneuvering: comfortable

For a hypothetical 50 kg eagle (s ~ 2.2):
- Basal metabolic rate: ~90 W
- Required flight power: ~800 W
- Maximum metabolic output: ~250 W
- **Deficit: 550 W** -- the eagle cannot fly under its own power

**Why Large Birds Soar Instead of Flapping**

This is precisely why condors, albatrosses, and pelicans soar. Soaring extracts energy from the environment (thermals, wind gradients) rather than generating it metabolically. A condor flaps only during takeoff and occasional altitude adjustments. An albatross can fly thousands of kilometers with almost no flapping by exploiting dynamic soaring over ocean waves.

Eagles themselves are accomplished soarers -- bald eagles often ride thermals for hours. But they retain the ability to flap for hunting dives and maneuvering. At larger size, even brief flapping becomes impossible.

**The Result**

The eagle's muscles burn through ATP faster than mitochondria can produce it. Flight attempts end in rapid exhaustion. Even if wing loading permits gliding, the eagle cannot take off, gain altitude, or execute hunting maneuvers.
    `.trim(),
    recoveryHint: 'Reduce body size to restore power-to-weight ratio.',
    proxyThreshold: POWER_THRESHOLD,
  },

  // =========================================================================
  // THERMOREGULATION FAILURE
  // =========================================================================
  THERMOREGULATION_FAILURE: {
    id: 'THERMOREGULATION_FAILURE',
    subsystem: 'thermo',
    severity: 'hard',
    title: 'Thermoregulation Failure',
    shortDescription: 'Overheating during flight. Heat dissipation cannot keep up with heat generation.',
    longDescription: `
**The Physics of Failure**

Flight muscles are heat engines with roughly 25% mechanical efficiency -- 75% of metabolic energy becomes waste heat. This heat must be dissipated to prevent lethal hyperthermia.

Heat dissipation occurs through:
- **Surface area** (radiation and convection), which scales as L^2
- **Respiratory evaporation** (panting), limited by lung capacity
- **Air sac ventilation** (unique to birds), also surface-area limited

Heat generation scales with metabolic rate and muscle volume (~ L^3).

**The Surface-Volume Collapse**

The surface-to-volume ratio scales as 1/L. A bird twice as long has 8x the volume but only 4x the surface area. Heat production doubles relative to dissipation capacity.

**Why Birds Lack Sweat Glands**

Unlike mammals, birds cannot sweat. Their primary cooling mechanisms are:
1. **Panting** -- evaporative cooling from the respiratory tract
2. **Gular fluttering** -- rapid vibration of the throat to increase evaporation
3. **Air sac ventilation** -- passing air through pneumatized bones
4. **Behavioral** -- seeking shade, soaking feet, altitude adjustment

All of these scale poorly with size. Panting requires respiratory effort that itself generates heat. Air sac cooling is surface-area limited.

**The Result**

During flight at this size, core body temperature rises uncontrollably. The eagle faces lethal hyperthermia within minutes of sustained activity. Flight becomes thermally impossible before it becomes mechanically impossible -- the muscles can generate the forces, but the heat would cook the bird from the inside out.
    `.trim(),
    recoveryHint: 'Reduce body size or operate in very cold environments.',
    proxyThreshold: THERMO_THRESHOLD,
  },
};

// -- Utility functions --------------------------------------------------------

/**
 * Get failure mode definition by ID.
 */
export const getFailureMode = (id: string): FailureModeDefinition | undefined => {
  return FAILURE_MODES[id];
};

/**
 * Get all failure modes for a specific subsystem.
 */
export const getFailureModesForSubsystem = (subsystem: Subsystem): FailureModeDefinition[] => {
  return Object.values(FAILURE_MODES).filter(fm => fm.subsystem === subsystem);
};

/**
 * Check if a specific proxy value has crossed the failure threshold.
 */
export const isProxyInFailure = (proxyValue: number, threshold: number): boolean => {
  return proxyValue < threshold;
};

/**
 * Detect all active failures based on current proxy values.
 */
export const detectFailures = (proxies: ScalingProxies): string[] => {
  const activeFailureIds: string[] = [];

  if (isProxyInFailure(proxies.wingLoading, FAILURE_MODES.WING_LOADING_FAILURE.proxyThreshold)) {
    activeFailureIds.push('WING_LOADING_FAILURE');
  }

  if (isProxyInFailure(proxies.bone, FAILURE_MODES.BONE_STRUCTURAL_FAILURE.proxyThreshold)) {
    activeFailureIds.push('BONE_STRUCTURAL_FAILURE');
  }

  if (isProxyInFailure(proxies.power, FAILURE_MODES.METABOLIC_POWER_DEFICIT.proxyThreshold)) {
    activeFailureIds.push('METABOLIC_POWER_DEFICIT');
  }

  if (isProxyInFailure(proxies.thermo, FAILURE_MODES.THERMOREGULATION_FAILURE.proxyThreshold)) {
    activeFailureIds.push('THERMOREGULATION_FAILURE');
  }

  return activeFailureIds;
};
